### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by SanjunLiu** [xjsxujingsong/FairMOT_TensorRT_C#2]
I use the method FromFile("detconfig.method = DetectorMethod::FromFile;") by saving the inter  results output from model:
f = open('tmp_data/%03d.size'%self.frame_id, 'wt')
f.write('%d %d %d %d'%(dets.shape[0], dets.shape[1], id_feature.shape[0], id_feature.shape[1]))
f.close()
dets.tofile('tmp_data/%03d.det'%self.frame_id)
id_feature.tofile('tmp_data/%03d.feature'%self.frame_id)
when i run this project, Segmentation fault has happened:
Segmentation fault (core dumped)

**Comment by xjsxujingsong** [comment]
Hi, I think you may use my old repository which has been removed due to some bugs. Previously, I dumped the detection result and reid feature from the original FairMOT python code to make sure my C++ conversion of tracking part is correct. So now you have generated detection result and reid feature, but the C++ code does not work? Can you step by step to debug and make sure where the bug is?

**Comment by SanjunLiu** [comment]
Yes, I have dumped the detection result and reid feature as it said in "https://github.com/intjun/FairMOT-C" by adding the following codes:
    id_feature = id_feature[remain_inds]
    f = open('tmp_data/%03d.size'%self.frame_id, 'wt')
    f.write('%d %d %d %d'%(dets.shape[0], dets.shape[1], id_feature.shape[0], id_feature.shape[1]))
    f.close()
    dets.tofile('tmp_data/%03d.det'%self.frame_id)
    id_feature.tofile('tmp_data/%03d.feature'%self.frame_id)
Firstly, the results is wrong, and also the segmentation fault has happened when run the second frame to start tracking

**Comment by SanjunLiu** [comment]
That would be very grateful if you could help to offer the converted model or the converted "tmp_data" which you have used in this project.

**Comment by SanjunLiu** [comment]
I use this project "https://github.com/intjun/FairMOT-C", It has been worked. Ofcouse, it the same with you offered codes "https://github.com/xjsxujingsong/FairMOT_TensorRT_C". 
Thank you grateful.

**Comment by xjsxujingsong** [comment]
Hi the old code has been removed before due to some bugs. Pls use this new version. BTW, do you still need the trained model?
