### ISSUE TITLE
Performance FPS

### ISSUE THREAD

**Issue by vuminhduc97** [xjsxujingsong/FairMOT_TensorRT_C#3]
thank for your useful repo!
How is the engine's performance?(DCN and not DCN)
How does it compare to pytorch?

**Comment by xjsxujingsong** [comment]
I did not do accurate comparsion between C++ and Python. It looks like they have similar speed.

**Comment by vuminhduc97** [comment]
It's strange , as far as I know the inference speed of trt is several dozen times greater than pth
