### ISSUE TITLE
如何编译

### ISSUE THREAD

**Issue by liu0623** [xjsxujingsong/FairMOT_TensorRT_C#7]
大佬你好，我是个小白，我在你的项目中没有看到cmakelist.txt请问如何编译

**Comment by xjsxujingsong** [comment]
我是在Windows平台开发的，所以直接用的visual studio.在Linux的话 你可以参考tensorrt的cmakelist

**Comment by liu0623** [comment]
好的，谢谢大佬，这个问题我已经解决了。
我还有个问题，请问您对heatmap的处理方式是怎样的以及bbox是如何生成的，我没有看到类似于寻找Topk的代码，我在您的代码中找到以下几行，您可以讲解一下吗
![2022-04-28 16-11-39 的屏幕截图](https://user-images.githubusercontent.com/69301683/165707991-2a90b6b4-f5dd-49cf-9311-f9bd7ddce0dd.png)

**Comment by xjsxujingsong** [comment]
对照python 代码，我是把nms和topk 放到cpp里面来处理的，但是nms里面的3x3 max pooling我是在python导出onnx的时候提前做好的

**Comment by liu0623** [comment]
不好意思又来打扰您，请问detection.cpp的第465行代码是什么意思啊，我对照python代码没有看明白
/home/liu/图片/2022-05-05 15-53-26 的屏幕截图.png

**Comment by liu0623** [comment]
不好意思又来打扰您，请问detection.cpp的第465行代码是什么意思啊，我对照python代码没有看明白
![2022-05-05 15-53-26 的屏幕截图](https://user-images.githubusercontent.com/69301683/166884284-3ec1a13b-07f7-4ad7-b4a2-42c7f8fa9ac7.png)

**Comment by xjsxujingsong** [comment]
这个是python 里面的 nms函数里面的 keep 替换。相当于maxpool之后，找到每个local最大值。最大值pool之后还是最大值
